exclude:
- Gemfile

#Site settings
theme: jekyll-theme-minimal
title: "Jessica Godwin"
description: >
  Ph.D. Candidate | CSDE Fellow <br />
  Makes a mean cornbread
logo: "/Images/godwin.jpg"
encoding: utf-8
lang: en-US
url: "https://jlgodwin.github.io"
#repo: "https://github.com/jlgodwin/jlgodwin.github.io"
email: "jlg0003@uw.edu"

#plugins:
#- jekyll-sitemap
#- jekyll-mentions
#- jekyll-paginate
#- jekyll-seo-tag
#- jekyll-redirect-from
#- jekyll-default-layout
#- jekyll-feed
#- jemoji
#- jekyll-remote-theme

# Site navigation
navigation_header:
 Home: /
#- title: "CV"
#  url: ./CV.pdf
#- title: "Twitter"
#  url: https://www.twitter.com/j_l_godwin
 Teaching: /
#- title: "Github"
 # url: https://github.com/jlgodwin
