#Site settings
theme: jekyll-theme-minimal
title: "Jessica Godwin"
description: "Ph.D. Candidate\n\n University of Washington Dept. of Statistics\n\n CSDE Fellow" 
logo: "./godwin.jpg"
encoding: utf-8
lang: en-US
url: "https://jlgodwin.github.io"
repo: "https://github.com/jlgodwin/jlgodwin.github.io"
email: "jlg0003@uw.edu"
logo: "godwin.jpg"

# Site navigation
navigation_header:
 Home: /
 #CV: /Files/CV.pdf
 #Teaching:
 Github: https://github.com/jlgodwin
