#Site settings
theme: jekyll-theme-minimal
title: "Jessica Godwin"
description: |
  Ph.D. Candidate
  University of Washington Dept. of Statistics
  CSDE Fellow
logo: "/Images/godwin.jpg"
encoding: utf-8
lang: en-US
url: "https://jlgodwin.github.io"
repo: "https://github.com/jlgodwin/jlgodwin.github.io"
email: "jlg0003@uw.edu"

# Site navigation
navigation_header:
 Home: /
 #CV: /Files/CV.pdf
 #Teaching:
 Github: https://github.com/jlgodwin
