theme: jekyll-theme-minimal
title: "Jessica Godwin"
description: "Ph.D. Candidate, University of Washington Dept. of Statistics | CSDE Fellow | MPIDR" 
logo: "./godwin.jpg"
encoding: utf-8
lang: en-US
url: "https://jlgodwin.github.io"
repo: "https://github.com/jlgodwin/jlgodwin.github.io"
email: "jlg0003@uw.edu"
logo: "godwin.jpg"